// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryMutator.Tests;

namespace QueryMutator.Tests.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QueryMutator.Tests.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntityProperty");

                    b.Property<string>("Ignored");

                    b.Property<string>("Name");

                    b.Property<int?>("SmallDogId");

                    b.HasKey("Id");

                    b.HasIndex("SmallDogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityProperty = 5,
                            Ignored = "IGNORE!",
                            Name = "Bodri",
                            SmallDogId = 1
                        },
                        new
                        {
                            Id = 2,
                            EntityProperty = 10,
                            Name = "Pimpedli",
                            SmallDogId = 2
                        });
                });

            modelBuilder.Entity("QueryMutator.Tests.SmallDog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SmallDogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small Bodri"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Small Pimpedli"
                        });
                });

            modelBuilder.Entity("QueryMutator.Tests.Dog", b =>
                {
                    b.HasOne("QueryMutator.Tests.SmallDog", "SmallDog")
                        .WithMany()
                        .HasForeignKey("SmallDogId");
                });
#pragma warning restore 612, 618
        }
    }
}
